### ISSUE TITLE
Question: Kinematics Support

### ISSUE THREAD

**Issue by jmwright** [fragmuffin/cqparts#101]
I think I've seen a brief mention of support for doing animation of assemblies. It seems like kinematics would be a natural fit too. Is there any intention/interest in supporting kinematics at some point?

**Comment by fragmuffin** [comment]
I think introducing kinematics directly to `cqparts` would be out of scope.
However, exporting / importing an `Assembly` to an external format that **does** support kinematics is definitely within scope.

I would imagine supporting something like [ROS](http://www.ros.org/) and the [Unified Robot Description Format (urdf)](http://wiki.ros.org/urdf) would be a good start!

**Comment by jmwright** [comment]
ROS had crossed my mind. Thanks!

**Comment by fragmuffin** [comment]
I passed the test 😊
