### ISSUE TITLE
Bearings

### ISSUE THREAD

**Issue by fragmuffin** [fragmuffin/cqparts#3]
Add some bearings:

- [x] ball bearing (2 concentric rings separated by spherical balls)
- [ ] tapered roller bearing

**Comment by fragmuffin** [comment]
```python
from cqparts.display import display
from cqparts_bearings.ball import BallBearing
display(BallBearing())
```
![ball-bearing](https://user-images.githubusercontent.com/2626190/35803600-75ff163a-0ac8-11e8-8f6a-2e93b728c186.png)

**Comment by jmwright** [comment]
Cool!
