### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by jmwright** [fragmuffin/cqparts#60]
@fragmuffin Not sure if you're on the CadQuery Google Group. This seems like the sort of thing cqparts was created for. https://groups.google.com/forum/m/#!msg/cadquery/WkBBXF6N7-Y/jnoM_4rCBQAJ

**Comment by fragmuffin** [comment]
@jmwright 
Thanks for alerting me to this... yes, that's exactly what it's made for.
Or rather, that's what half of it was made for ;)

I've applied to be a member of the group, I'l reply once that goes through.

**Comment by jmwright** [comment]
It looks like you've been approved. Dave and I are the moderators. Let me know if you have issues.

**Comment by fragmuffin** [comment]
Thanks @jmwright !
