### ISSUE TITLE
How to Search PyPi for cqparts

### ISSUE THREAD

**Issue by jmwright** [fragmuffin/cqparts#73]
The readme gives the following line as a way to search for cqparts related packages on PyPi.
```
pip search cqparts_
```
However, using the underscore doesn't work for me. You either need to search just `cqparts` or `cqparts-`.

**Comment by fragmuffin** [comment]
@jmwright good catch! and it's in the main readme too!

**Comment by fragmuffin** [comment]
just corrected in 9de5ec3cc4b1257107e149e2b8a3bd2f72230e32
